---
 - name: playbook01
   hosts: all
   become: True



   tasks:
     - name: Find
       ansible.builtin.find:
        paths: /var/log
        file_type: file
        patterns: '*.log'
       register: output_find

     - name: output
       ansible.builtin.debug:
         var: output_find
